name: main
run-name: main-pipeline
on: [push]
jobs:

  deploy:
    needs: build-image
    runs-on: ubuntu-latest 
    - uses: actions/checkout@main
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.0
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: my-app-path
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: zaliczeniemj
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: my-app-path













#build - done
#test - done
#accept
#deploy
